Major fix

diff --git a/scripts/haploclique-assembly b/scripts/haploclique-assembly
--- a/scripts/haploclique-assembly
+++ b/scripts/haploclique-assembly
@@ -8,20 +8,21 @@ USAGE:     haploclique-assembly options...
 OPTIONS:
    -h      Show this message
    -r      Path to the reference genome (required)
-   -a      Path to the alignment in BAM format (required)
-   -q      Edge threshold for raw reads
-   -g      Edge threshold for error-corrected reads
-   -o      Minimal relative overlap
+   -i      Path to the alignment in BAM format (required)
+   -q      Edge threshold for error-corrected reads
+   -g      Edge threshold for raw reads
+   -o      Minimal relative overlap for error-corrected reads
+   -j      Minimal relative overlap for raw reads
    -c      Maximal coverage
    -s      Minimal clique size
    -p      PacBio alignment with InDelFixer
-   -i      InDelFixer alignment
+   -a      InDelFixer alignment
    -t      Number of iterations
    -u      Shuffle in parallelization
    -e      Continue assembly
    -z      Split size
    -x      Split size for singletons
-   -g      No parallelization
+   -G      No parallelization
    -w      Do not re-use singletons
    -n      Do not use alignment prior
    -l      Only predict indels, no haplotypes
@@ -50,14 +51,14 @@ NOSINGLETONS=0
 NOSKIPPING=0
 NOPRIOR=0
 INDEL=0
-while getopts “a:h:r:q:o:pt:c:s:euz:gwng:j:ilx:” OPTION
+while getopts “ah:r:q:o:pt:c:s:euz:Gwng:j:i:lx:” OPTION
 do
      case $OPTION in
          h)
              usage
              exit 1
              ;;
-         a)
+         i)
              ALIGNMENT=$OPTARG
              ;;
          r)
@@ -85,7 +86,7 @@ do
              PACBIO=1
              INDELFIXER=1
              ;;
-         i)
+         a)
              INDELFIXER=1
              ;;
          t)
@@ -103,7 +104,7 @@ do
          x)
              SPLITSIZESINGLES=$OPTARG
              ;;
-         g)
+         G)
              NOPARALLEL=1
              ;;
          w)
@@ -133,6 +134,8 @@ echo $HQ > .HQ.parameter
 echo $HO > .HO.parameter
 echo $HC > .HC.parameter
 echo $HS > .HS.parameter
+echo $HG > .HG.parameter
+echo $HJ > .HJ.parameter
 if [[ $REF == ~/* ]] || [[ $REF == /* ]]; then
     echo $REF > .REF.parameter
 else
@@ -144,34 +147,34 @@ echo $NOPRIOR > .NOPRIOR.parameter
 echo $INDEL > .INDEL.parameter
 
 function initial() {
-    samtools view -uf 1 $ALIGNMENT > paired.bam #2> /dev/null
-    samtools view -uF 1 $ALIGNMENT > single.bam #2> /dev/null
-    java -jar $SAF/ConsensusFixer.jar -i $ALIGNMENT --stats -s #2>&1 > /dev/null
-    samtools sort -n single.bam single_sort #2>&1 > /dev/null 
-    samtools view single_sort.bam | head > single_sort.sam #2> /dev/null
-    samtools view paired.bam | head > paired.sam #2> /dev/null
+    samtools view -uf 1 $ALIGNMENT > paired.bam 2> /dev/null
+    samtools view -uF 1 $ALIGNMENT > single.bam 2> /dev/null
+    java -jar $SAF/ConsensusFixer.jar -i $ALIGNMENT --stats -s 2>&1 > /dev/null
+    samtools sort -n single.bam single_sort 2> /dev/null > /dev/null
+    samtools view single_sort.bam 2> /dev/null | head > single_sort.sam 2> /dev/null
+    samtools view paired.bam 2> /dev/null | head > paired.sam 2> /dev/null
 
     touch paired.priors single.priors
     if [ -s paired.sam ]; then
-        bam-to-alignment-priors -m mean-sd $REF paired.bam > paired.priors #2> /dev/null
+        bam-to-alignment-priors -m mean-sd $REF paired.bam > paired.priors 2> /dev/null
     fi
     if [ -s single_sort.sam ]; then
-        bam-to-alignment-priors --unsorted --single-end $REF single_sort.bam > single.priors #2> /dev/null
+        bam-to-alignment-priors --unsorted --single-end $REF single_sort.bam > single.priors 2> /dev/null
     fi
     if [ $INDEL == 0 ]; then
         if [ -s data_clique_to_reads.tsv ]; then
-            cat paired.priors single.priors  | manipulate_alignment_prior.py data_clique_to_reads.tsv > alignment.prior #2> /dev/null
+            cat paired.priors single.priors  | manipulate_alignment_prior.py data_clique_to_reads.tsv > alignment.prior 2> /dev/null
         else
-            cat paired.priors single.priors > alignment.prior #2> /dev/null
+            cat paired.priors single.priors > alignment.prior 2> /dev/null
         fi
     else
         if [ -s data_clique_to_reads.tsv ]; then
-            cat paired.priors  | manipulate_alignment_prior.py data_clique_to_reads.tsv > alignment.prior #2> /dev/null
+            cat paired.priors  | manipulate_alignment_prior.py data_clique_to_reads.tsv > alignment.prior 2> /dev/null
         else
-            mv paired.priors alignment.prior #2> /dev/null
+            mv paired.priors alignment.prior 2> /dev/null
         fi
     fi
-    rm *sam *bam *.priors #2>&1 > /dev/null
+    rm *sam *bam *.priors 2>&1 > /dev/null
 }
 
 function assemble() {
@@ -182,7 +185,7 @@ function assemble() {
 
     function idf ()
     {
-        java -Xmx4g -XX:+UseParallelGC -XX:NewRatio=9 -jar ~/Dropbox/QuasiAsterisk/InDelFixer/target/InDelFixer.jar $* #2>&1 > /dev/null
+        java -Xmx4g -XX:+UseParallelGC -XX:NewRatio=9 -jar ~/Dropbox/QuasiAsterisk/InDelFixer/target/InDelFixer.jar $* 2>&1 > /dev/null
     }
     function alignMemPaired () {
         if [ $INDELFIXER == 1 ]; then
@@ -193,15 +196,15 @@ function assemble() {
             fi
             mv reads.sam aln.sam
         else
-            bwa index $2 #2> /dev/null > /dev/null
-            bwa mem -t 79 $2 $1 $3 > aln.sam #2> /dev/null
+            bwa index $2 2> /dev/null > /dev/null
+            bwa mem -t 79 $2 $1 $3 > aln.sam 2> /dev/null
         fi
-        samtools faidx $2 #2>&1 > /dev/null
-        samtools view -q 20 -F 4 -bt $REF.fai aln.sam > aln.bam #2> /dev/null
-        samtools sort aln.bam reads #2>&1 > /dev/null
-        rm aln* #2>&1 > /dev/null
-        samtools view -uf 1 reads.bam > paired.bam #2> /dev/null
-        samtools view -uF 1 reads.bam > single_1.bam #2> /dev/null
+        samtools faidx $2 2>&1 > /dev/null
+        samtools view -q 20 -F 4 -bt $REF.fai aln.sam > aln.bam 2> /dev/null
+        samtools sort aln.bam reads 2>&1 > /dev/null
+        rm aln* 2>&1 > /dev/null
+        samtools view -uf 1 reads.bam > paired.bam 2> /dev/null
+        samtools view -uF 1 reads.bam > single_1.bam 2> /dev/null
         rm reads.bam
     }
     function alignMemSingle () {
@@ -213,13 +216,13 @@ function assemble() {
             fi
             mv reads.sam aln.sam
         else
-            bwa index $2 #2> /dev/null > /dev/null
+            bwa index $2 2> /dev/null > /dev/null
             bwa mem -t 79 $2 $1 > aln.sam
         fi
-        samtools faidx $2 #2>&1 > /dev/null
-        samtools view -q 20 -F 4 -bt $REF.fai aln.sam > aln.bam #2> /dev/null
-        samtools sort aln.bam single_2 #2>&1 > /dev/null
-        rm aln* #2>&1 > /dev/null
+        samtools faidx $2 2>&1 > /dev/null
+        samtools view -q 20 -F 4 -bt $REF.fai aln.sam > aln.bam 2> /dev/null
+        samtools sort aln.bam single_2 2>&1 > /dev/null
+        rm aln* 2>&1 > /dev/null
     }
     if [[ -s $FORWARD ]] && [[ -s $BACKWARD ]]; then
         alignMemPaired $FORWARD $REF $BACKWARD
@@ -228,7 +231,7 @@ function assemble() {
     if [ -s $SINGLE ]; then
         alignMemSingle $SINGLE $REF
         if [ -s single_1.bam ]; then
-            samtools merge single.bam single_1.bam single_2.bam #2>&1 > /dev/null
+            samtools merge single.bam single_1.bam single_2.bam 2>&1 > /dev/null
         else
             mv single_2.bam single.bam
         fi
@@ -239,52 +242,54 @@ function assemble() {
     fi
 
     if [[ -s single.bam ]] && [[  -s paired.bam ]]; then
-        samtools merge reads_unsorted.bam single.bam paired.bam #2>&1 > /dev/null
-        samtools sort reads_unsorted.bam assembly #2>&1 > /dev/null
-        samtools index assembly.bam #2>&1 > /dev/null
+        samtools merge reads_unsorted.bam single.bam paired.bam 2>&1 > /dev/null
+        samtools sort reads_unsorted.bam assembly 2>&1 > /dev/null
+        samtools index assembly.bam 2>&1 > /dev/null
 
-        java -jar $SAF/ConsensusFixer.jar -i assembly.bam --stats -s #2>&1 > /dev/null
+        java -jar $SAF/ConsensusFixer.jar -i assembly.bam --stats -s 2>&1 > /dev/null
     elif [[ -s single.bam ]]; then
-        samtools sort single.bam assembly #2>&1 > /dev/null
-        samtools index assembly.bam #2>&1 > /dev/null
+        samtools sort single.bam assembly 2>&1 > /dev/null
+        samtools index assembly.bam 2>&1 > /dev/null
 
-        java -jar $SAF/ConsensusFixer.jar -i assembly.bam --stats -s #2>&1 > /dev/null
+        java -jar $SAF/ConsensusFixer.jar -i assembly.bam --stats -s 2>&1 > /dev/null
     elif [[ -s paired.bam ]]; then
-        samtools sort paired.bam assembly #2>&1 > /dev/null
-        samtools index assembly.bam #2>&1 > /dev/null
+        samtools sort paired.bam assembly 2>&1 > /dev/null
+        samtools index assembly.bam 2>&1 > /dev/null
 
-        java -jar $SAF/ConsensusFixer.jar -i assembly.bam --stats -s #2>&1 > /dev/null
+        java -jar $SAF/ConsensusFixer.jar -i assembly.bam --stats -s 2>&1 > /dev/null
     fi
 
      rm -rf assembly*
 
     if [[ -s single.bam ]]; then
-        samtools sort -n single.bam single_sort #2>&1 > /dev/null
-        samtools view single_sort.bam > single_sort.sam #2> /dev/null
+        samtools sort -n single.bam single_sort 2>&1 > /dev/null
+        samtools view single_sort.bam > single_sort.sam 2> /dev/null
     fi
     if [[  -s paired.bam ]]; then
-        samtools view paired.bam > paired.sam #2> /dev/null
+        samtools view paired.bam > paired.sam 2> /dev/null
     fi
 
     touch paired.priors single.priors
     if [ -s paired.sam ]; then
-        bam-to-alignment-priors $REF paired.bam > paired.priors #2> /dev/null
+        bam-to-alignment-priors $REF paired.bam > paired.priors 2> /dev/null
     fi
     if [ -s single_sort.sam ]; then
-        bam-to-alignment-priors --unsorted --single-end $REF single_sort.bam > single.priors #2> /dev/null
+        bam-to-alignment-priors --unsorted --single-end $REF single_sort.bam > single.priors 2> /dev/null
     fi
     if [ -s data_clique_to_reads.tsv ]; then
-        cat paired.priors single.priors | manipulate_alignment_prior.py data_clique_to_reads.tsv > alignment.prior #2> /dev/null
+        cat paired.priors single.priors | manipulate_alignment_prior.py data_clique_to_reads.tsv > alignment.prior 2> /dev/null
     else
         cat paired.priors single.priors > alignment.prior
     fi
-    rm -rf *sam *bam *.priors #2> /dev/null
+    rm -rf *sam *bam *.priors 2> /dev/null
 }
 
 function computeParallelSingle() {
     cd $1
     HQ=`cat ../.HQ.parameter`
     HO=`cat ../.HO.parameter`
+    HG=`cat ../.HG.parameter`
+    HJ=`cat ../.HJ.parameter`
     HC=`cat ../.HC.parameter`
     HS=`cat ../.HS.parameter`
     NOPRIOR=`cat ../.NOPRIOR.parameter`
@@ -293,19 +298,19 @@ function computeParallelSingle() {
 
     if [ $INDEL == 0 ]; then
         if [[ $NOPRIOR == 1 ]];then
-            cat alignment.prior | sort -k6,6 -g | haploclique -c $HC -s $HS -q $HQ -o $HO -a -m > data_clique.fastq;
+            cat alignment.prior | sort -k6,6 -g | haploclique -c $HC -s $HS -q $HQ -o $HO -j $HJ -g $HG -a -m > data_clique.fastq;
         else
-            cat alignment.prior | sort -k6,6 -g | haploclique -A ../statistics.txt -c $HC -s $HS -q $HQ -o $HO -a -m > data_clique.fastq;
+            cat alignment.prior | sort -k6,6 -g | haploclique -A ../statistics.txt -c $HC -s $HS -q $HQ -o $HO -j $HJ -g $HG -a -m > data_clique.fastq;
         fi
     else
         if [[ $NOPRIOR == 1 ]];then
-            cat alignment.prior | sort -k6,6 -g | haploclique -M ../mean-sd -I indel.out -c $HC -s $HS -q $HQ -o $HO -a -m > data_clique.fastq;
+            cat alignment.prior | sort -k6,6 -g | haploclique -M ../mean-sd -I indel.out -c $HC -s $HS -q $HQ -o $HO -j $HJ -g $HG -a -m > data_clique.fastq;
         else
-            cat alignment.prior | sort -k6,6 -g | haploclique -M ../mean-sd -I indel.out -A ../statistics.txt -c $HC -s $HS -q $HQ -o $HO -a -m > data_clique.fastq;
+            cat alignment.prior | sort -k6,6 -g | haploclique -M ../mean-sd -I indel.out -A ../statistics.txt -c $HC -s $HS -q $HQ -o $HO -j $HJ -g $HG -a -m > data_clique.fastq;
         fi
     fi
     haploclique-postprocess.py < data_clique.fastq
-    rm -rf data_clique.fastq support
+    #rm -rf data_clique.fastq support
 
     sed -i -e '/^$/d;s/@Clique1/@Clique'"$1"'/g' data_cliques_paired_R1.fastq
     sed -i -e '/^$/d;s/@Clique2/@Clique'"$1"'/g' data_cliques_paired_R2.fastq
@@ -323,10 +328,25 @@ function compute() {
     HO=`cat .HO.parameter`
     HC=`cat .HC.parameter`
     HS=`cat .HS.parameter`
+    HG=`cat .HG.parameter`
+    HJ=`cat .HJ.parameter`
     #echo -e "Parameter q/o:\t\t${HQ}/${HO}"
-    cat alignment.prior | sort -k6,6 -g | haploclique -A statistics.txt -c $HC -s $HS -q $HQ -o $HO -a -m > data_clique.fastq;
+    if [ $INDEL == 0 ]; then
+        if [[ $NOPRIOR == 1 ]];then
+            cat alignment.prior | sort -k6,6 -g | haploclique -c $HC -s $HS -q $HQ -o $HO -j $HJ -g $HG -a -m > data_clique.fastq;
+        else
+            cat alignment.prior | sort -k6,6 -g | haploclique -A statistics.txt -c $HC -s $HS -q $HQ -o $HO -j $HJ -g $HG -a -m > data_clique.fastq;
+        fi
+    else
+        if [[ $NOPRIOR == 1 ]];then
+            cat alignment.prior | sort -k6,6 -g | haploclique -M mean-sd -I indel.out -c $HC -s $HS -q $HQ -o $HO -j $HJ -g $HG -a -m > data_clique.fastq;
+        else
+            cat alignment.prior | sort -k6,6 -g | haploclique -M mean-sd -I indel.out -A statistics.txt -c $HC -s $HS -q $HQ -o $HO -j $HJ -g $HG -a -m > data_clique.fastq;
+        fi
+    fi
+    #cat alignment.prior | sort -k6,6 -g | haploclique -A statistics.txt -c $HC -s $HS -q $HQ -o $HO -j $HJ -g $HG -a -m > data_clique.fastq;
     haploclique-postprocess.py < data_clique.fastq
-    rm -rf data_clique.fastq support
+    #rm -rf data_clique.fastq support
 
     sed -i -e '/^$/d;s/@Clique1/@Clique/g' data_cliques_paired_R1.fastq
     sed -i -e '/^$/d;s/@Clique2/@Clique/g' data_cliques_paired_R2.fastq
@@ -340,23 +360,16 @@ function compute() {
 
 export -f computeParallelSingle
 
-if [[ $CONTINUE == 0 ]]; then
+if [[ ! -s alignment.prior ]]; then
     initial
 fi
 
 if [[ $NOPARALLEL == 0 ]]; then
     for i in $(seq 1 ${ITERATIONS}); do
         if [[ $NOSINGLETONS == 0 ]]; then
-            cat singles.prior >> alignment.prior
+            cat singles.prior >> alignment.prior 2> /dev/null
         fi
-        if [[ $CONTINUE == 0 ]]; then
-            echo $HG > .HQ.parameter
-            echo $HJ > .HO.parameter
-        else
-            echo $HQ > .HQ.parameter
-            echo $HO > .HO.parameter
-        fi
-        rm -rf skipped.prior singles.prior old.prior data* trash* *-e x*
+        rm -rf skipped.prior singles.prior old.prior data* trash* *-e x* 2> /dev/null
         if [[ $SHUFFLE == 1 ]]; then
             cat alignment.prior | awk 'BEGIN{srand();}{print rand()"\t"$0}' | sort -k1 -n | cut -f2- | split -l $SPLITSIZE -a 10
             for i in x*; do mkdir $i-dir; mv $i $i-dir/alignment.prior; rm $i; done
@@ -366,11 +379,9 @@ if [[ $NOPARALLEL == 0 ]]; then
         fi
 
         parallel computeParallelSingle {} ::: x*-dir
-        rm -rf data*
+        #rm -rf data*
         if [[ $NOSINGLETONS == 0 ]]; then
-            echo "SINGLES"
-            echo $HG > .HQ.parameter
-            echo $HJ > .HO.parameter
+            echo "Error correction"
             # for i in $(seq 1 3); do
             cat x*/data_cliques_paired_R1.fastq >> data_cliques_paired_R1.fastq
             cat x*/data_cliques_paired_R2.fastq >> data_cliques_paired_R2.fastq
@@ -379,9 +390,9 @@ if [[ $NOPARALLEL == 0 ]]; then
             sed -i -e '/^$/d;s/Clique/Clique_/g' data*
             #cat data_cliques_* | awk '{if (NR%4==2) { l += length($0);i++}} END {printf("Mean/max read length:\t\t%.0f/",l/i)}'
             cat data_cliques_* | awk 'BEGIN {l = 0} {if (NR%4==2 && l < length($0)) l = length($0)} END {printf("Max read length:\t\t%.0f bp\n",l)}'
-            cat x*/singles.prior | sort -u -t" " -k1,1 | sort -k6,6 -g > alignment.prior
-            cat x*/skipped.prior > skipped.prior
-            rm -rf trash* *-e x*
+            cat x*/singles.prior | sort -u -t" " -k1,1 | sort -k6,6 -g > alignment.prior 2> /dev/null
+            cat x*/skipped.prior > skipped.prior 2> /dev/null
+            rm -rf trash* *-e x* 2> /dev/null
             if [[ $SHUFFLE == 1 ]]; then
                 cat alignment.prior | awk 'BEGIN{srand();}{print rand()"\t"$0}' | sort -k1 -n | cut -f2- | split -l $SPLITSIZESINGLES -a 10
                 for i in x*; do mkdir $i-dir; cat $i | sort -u -t" " -k1,1  | sort -k6,6 -g  > $i-dir/alignment.prior; rm $i; done
@@ -394,9 +405,7 @@ if [[ $NOPARALLEL == 0 ]]; then
             cat x*/singles.prior | sort -u -t" " -k1,1 > singles.prior
         fi
         if [[ $NOSKIPPING == 0 ]] && [[ -s skipped.prior ]]; then
-            echo "SKIPPED"
-            echo $HG > .HQ.parameter
-            echo $HJ > .HO.parameter
+            echo "Computing skipped reads"
             # for i in $(seq 1 3); do
             cat x*/data_cliques_paired_R1.fastq >> data_cliques_paired_R1.fastq
             cat x*/data_cliques_paired_R2.fastq >> data_cliques_paired_R2.fastq
@@ -442,36 +451,22 @@ if [[ $NOPARALLEL == 0 ]]; then
         CONTINUE=1
     done
 else
-    if [[ $CONTINUE == 0 ]]; then
-        echo $HG > .HQ.parameter
-        echo $HJ > .HO.parameter
-    else
-        echo $HQ > .HQ.parameter
-        echo $HO > .HO.parameter
-    fi
     for i in $(seq 1 ${ITERATIONS}); do
-        echo "C1"
+        if [[ $NOSINGLETONS == 0 ]]; then
+            sort -u -t" " -k1,1 singles.prior >> alignment.prior 2> /dev/null
+            rm -rf singles.prior 2> /dev/null
+        fi
+        rm -rf skipped.prior old.prior data* trash* *-e x* 2> /dev/null
         compute
-        echo "A1"
+        if [[ $INDEL == 1 ]];then
+            cat x*/indel.out >> indel.out
+            postprocess-predictions --stddev `cat mean-sd | cut -f2 -d" "` indel.out `cat mean-sd | cut -f1 -d" "` --vcf > indel.vcf
+            rm -rf x* alignment.prior mean-sd support
+            exit 1
+        fi
         assemble
-        echo "X1"
         # cat data_cliques_* | awk '{if (NR%4==2) { l += length($0);i++}} END {printf("Mean/max read length:\t\t%.0f/",l/i)}'
         cat data_cliques_* | awk 'BEGIN {l = 0} {if (NR%4==2 && l < length($0)) l = length($0)} END {printf("Max read length:\t\t%.0f bp\n",l)}'
-        echo $HQ > .HQ.parameter
-        echo $HO > .HO.parameter
         cat skipped.prior >> alignment.prior
     done
 fi
-
-#parallel parallelGlobal {} ::: x*-dir
-#REF=$OLDREF
-#cat x*/data_cliques_paired_R1.fastq > data_cliques_paired_R1.fastq
-#cat x*/data_cliques_paired_R2.fastq > data_cliques_paired_R2.fastq
-#cat x*/data_cliques_single.fastq > data_cliques_single.fastq
-#cat x*/data_clique_to_reads.tsv > data_clique_to_reads.tsv
-
-#for i in $(seq 1 ${ITERATIONS}); do
-
-    #rm -rf x*
-#done
-#globalAssembly
