Check update

diff --git a/scripts/haploclique-assembly b/scripts/haploclique-assembly
--- a/scripts/haploclique-assembly
+++ b/scripts/haploclique-assembly
@@ -144,14 +144,14 @@ do
      esac
 done
 
-command -v haploclique >/dev/null 2>&1 || { echo >&2 "I require haploclique but it's not installed.  Aborting."; exit 1; }
-command -v haploclique-assembly >/dev/null 2>&1 || { echo >&2 "I require haploclique-assembly but it's not installed.  Aborting."; exit 1; }
-command -v samtools >/dev/null 2>&1 || { echo >&2 "I require samtools but it's not installed.  Aborting."; exit 1; }
-command -v bam-to-alignment-priors >/dev/null 2>&1 || { echo >&2 "I require bam-to-alignment-priors but it's not installed.  Aborting."; exit 1; }
-command -v java >/dev/null 2>&1 || { echo >&2 "I require java but it's not installed.  Aborting."; exit 1; }
-command -v seeksingletons >/dev/null 2>&1 || { echo >&2 "I require seeksingletons but it's not installed.  Aborting."; exit 1; }
-command -v postprocess-predictions >/dev/null 2>&1 || { echo >&2 "I require postprocess-predictions but it's not installed.  Aborting."; exit 1; }
-command -v alignmentparser >/dev/null 2>&1 || { echo >&2 "I require alignmentparser but it's not installed.  Aborting."; exit 1; }
+hash haploclique >/dev/null 2>&1 || { echo >&2 "I require haploclique but it's not installed.  Aborting."; exit 1; }
+hash haploclique-assembly >/dev/null 2>&1 || { echo >&2 "I require haploclique-assembly but it's not installed.  Aborting."; exit 1; }
+hash samtools >/dev/null 2>&1 || { echo >&2 "I require samtools but it's not installed.  Aborting."; exit 1; }
+hash bam-to-alignment-priors >/dev/null 2>&1 || { echo >&2 "I require bam-to-alignment-priors but it's not installed.  Aborting."; exit 1; }
+hash java >/dev/null 2>&1 || { echo >&2 "I require java but it's not installed.  Aborting."; exit 1; }
+hash seeksingletons >/dev/null 2>&1 || { echo >&2 "I require seeksingletons but it's not installed.  Aborting."; exit 1; }
+hash postprocess-predictions >/dev/null 2>&1 || { echo >&2 "I require postprocess-predictions but it's not installed.  Aborting."; exit 1; }
+hash alignmentparser >/dev/null 2>&1 || { echo >&2 "I require alignmentparser but it's not installed.  Aborting."; exit 1; }
 
 if [[ -z $REF ]] || [[ -z $ALIGNMENT ]]
 then
